# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ebccefa225d567910745ef24812b8e7c0e4e95f3845eda2160f62a0969a6e3d900884dc1f644f8c3ad948766bd115729d97f8e8c563b8771a52227ce53d3799

test:
  secret_key_base: a24ad36a8465101f56edeab134a3a9cd84ea6516f55c618130257875afcda497113ff4c0f83128986f9c9a80b99dd9ead6c542d9cc5570c0bc929c3a31fc21ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
